### ISSUE TITLE
ModuleNotFoundError: No module named 'MatterSim'

### ISSUE THREAD

**Issue by lizixiaoboluo** [peteanderson80/Matterport3DSimulator#121]
(vlnhamt) tjf22@ubuntu:~/VLN-HAMT-main/finetune_src$ export PYTHONPATH=Matterport3DSimulator/build:/usr/bin/python3.6
(vlnhamt) tjf22@ubuntu:~/VLN-HAMT-main/finetune_src$ bash scripts/run_r2r.sh
Traceback (most recent call last):
  File "r2r/main.py", line 20, in <module>
    from finetune_src.r2r.agent_cmt import Seq2SeqCMTAgent
  File "../finetune_src/r2r/agent_cmt.py", line 22, in <module>
    from .eval_utils import cal_dtw
  File "../finetune_src/r2r/eval_utils.py", line 7, in <module>
    import MatterSim
ModuleNotFoundError: No module named 'MatterSim'
Traceback (most recent call last):
  File "r2r/main.py", line 20, in <module>
    from finetune_src.r2r.agent_cmt import Seq2SeqCMTAgent
  File "../finetune_src/r2r/agent_cmt.py", line 22, in <module>
    from .eval_utils import cal_dtw
  File "../finetune_src/r2r/eval_utils.py", line 7, in <module>
    import MatterSim
ModuleNotFoundError: No module named 'MatterSim'

**Comment by Routine113** [comment]
Hello，I have met the same question，do you have solved it？thank u

**Comment by lizixiaoboluo** [comment]
Yes,i do. You can enter the docker to run the program for invoking MatterSim.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 晚上8:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [peteanderson80/Matterport3DSimulator] ModuleNotFoundError: No module named &#39;MatterSim&#39; (Issue #121)





 
Hello，I have met the same question，do you have solved it？thank u

**Comment by Routine113** [comment]
> Yes,i do. You can enter the docker to run the program for invoking MatterSim.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年4月15日(星期六) 晚上8:38 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [peteanderson80/Matterport3DSimulator] ModuleNotFoundError: No module named &#39;MatterSim&#39; (Issue #121) Hello，I have met the same question，do you have solved it？thank u — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

I am running my program in Conda Env and I am always unable to import MatterSim. Do I have to reconfigure my environment in the Docker before importing MatterSim？
Thank you again for your patient answer！

**Comment by lizixiaoboluo** [comment]
Yes, you need to reconfigure your environment in the Docker and put the code in Mattersim's folder.&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 晚上9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [peteanderson80/Matterport3DSimulator] ModuleNotFoundError: No module named &#39;MatterSim&#39; (Issue #121)





  
Yes,i do. You can enter the docker to run the program for invoking MatterSim.
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年4月15日(星期六) 晚上8:38 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [peteanderson80/Matterport3DSimulator] ModuleNotFoundError: No module named 'MatterSim' (Issue #121) Hello，I have met the same question，do you have solved it？thank u — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
I am running my program in Conda Env and I am always unable to import MatterSim. Do I have to reconfigure my environment in the Docker before importing MatterSim？
 Thank you again for your patient answer！

**Comment by Routine113** [comment]
> Yes, you need to reconfigure your environment in the Docker and put the code in Mattersim's folder.&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年4月15日(星期六) 晚上9:02 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [peteanderson80/Matterport3DSimulator] ModuleNotFoundError: No module named &#39;MatterSim&#39; (Issue #121) Yes,i do. You can enter the docker to run the program for invoking MatterSim. … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年4月15日(星期六) 晚上8:38 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [peteanderson80/Matterport3DSimulator] ModuleNotFoundError: No module named 'MatterSim' (Issue #121) Hello，I have met the same question，do you have solved it？thank u — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; I am running my program in Conda Env and I am always unable to import MatterSim. Do I have to reconfigure my environment in the Docker before importing MatterSim？ Thank you again for your patient answer！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Thank you for your kind replying！！！I'm tring.

**Comment by Routine113** [comment]
Sorry to bother you again, I have successfully run the ‘VLNBERT’ project in Docker, but when I want to execute other projects, the installation environment for other projects is Python 3.8. But the built-in Python version in Docker is 3.6.9, so I cannot install the libraries required by other environments. I have tried to upgrade the Python version, but it has failed. Can you teach me how to solve this problem

**Comment by lukun927** [comment]
I have just overcomed this "can't find" problem by run the .py document by python3, what a surprise!
