### ISSUE TITLE
Downsizing a single Scan

### ISSUE THREAD

**Issue by HuzaifaSalahuddin** [peteanderson80/Matterport3DSimulator#128]
Hello Everyone!
I have not downloaded the entire Matterport3D release. Rather, I have downloaded only one scan with the house ID of 17DRP5sb8fy Now, whenever I try to run the downsize_skybox.py, it gives this error:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "./scripts/downsize_skybox.py", line 29, in downsizeWithMerge
    intrinsics,_ = camera_parameters(scan)
  File "/root/mount/Matterport3DSimulator/scripts/depth_to_skybox.py", line 55, in camera_parameters
    with open(camera_template % (base_dir,scan,scan)) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/v1/scans/2azQ1b91cZZ/undistorted_camera_parameters/2azQ1b91cZZ.conf'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./scripts/downsize_skybox.py", line 71, in <module>
    p.map(downsizeWithMerge, scans)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'data/v1/scans/2azQ1b91cZZ/undistorted_camera_parameters/2azQ1b91cZZ.conf'

This clearly shows it is looking for scans of other houses which I have not downloaded. For example in this case, it is looking for house with an ID of  **2azQ1b91cZZ** which was not downloaded. Is it necessary to download all of them? Or is there another way to resolve this issue. I would really appreciate any help on this issue.

**Comment by HuzaifaSalahuddin** [comment]
Oh, so it works by simply removing all of the house ID's that were not downloaded in the file scans.txt located at /Matterport3DSimulator/connectivity/scans.txt !
