### ISSUE TITLE
questions about image data

### ISSUE THREAD

**Issue by vincentlux** [peteanderson80/Matterport3DSimulator#60]
Hi,

I tried to run the preprocessing `./scripts/downsize_skybox.py` however got the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/v1/scans/17DRP5sb8fy/undistorted_camera_parameters/17DRP5sb8fy.conf'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./scripts/downsize_skybox.py", line 71, in <module>
    p.map(downsizeWithMerge, scans)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'data/v1/scans/17DRP5sb8fy/undistorted_camera_parameters/17DRP5sb8fy.conf'
```

The image data I used was downloaded using the `download_mp.py` several months ago. It appears that there was an inconsistency in image data? Is there any way I can fix it? Thanks for the help in advance!

**Comment by vincentlux** [comment]
Nevermind, I found that these are included in the download script, thanks!
