### ISSUE TITLE
Test failed due to wrong path

### ISSUE THREAD

**Issue by ZhangTianrong** [peteanderson80/Matterport3DSimulator#63]
When following the instructions in readme, `./build/tests ~Timing` results in the following error:
```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
tests is a Catch v2.0.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
RGB Image
-------------------------------------------------------------------------------
/root/mount/Matterport3DSimulator/src/test/main.cpp:342
...............................................................................

/root/mount/Matterport3DSimulator/src/test/main.cpp:373: FAILED:
  REQUIRE_NOTHROW( sim.newEpisode(scanIds, viewpointIds, headings, elevations) )
due to unexpected exception with messages:
  [
  	{
  		"elevation" : 0.0085573808395640535,
  		"heading" : 2.551961945320492,
  		"reference_image" : "17DRP5sb8fy_85c23efeaecd4d43a7dcd5b90137179e_2.
  551961945320492_0.008557380839564054.png",
  		"scanId" : "17DRP5sb8fy",
  		"viewpointId" : "85c23efeaecd4d43a7dcd5b90137179e"
  	},
  	{
  		"elevation" : 0.00049218360228025842,
  		"heading" : 1.8699330579409539,
  		"reference_image" : "1LXtFkjw3qL_187589bb7d4644f2943079fb949c0be9_1.
  8699330579409539_0.0004921836022802584.png",
  		"scanId" : "1LXtFkjw3qL",
  		"viewpointId" : "187589bb7d4644f2943079fb949c0be9"
  	},
  	{
  		"elevation" : -0.024443526143047459,
  		"heading" : 4.6263310475510773,
  		"reference_image" : "1pXnuDYAj8r_163d61ac7edb43fb958c5d9e69ae11ad_4.
  626331047551077_-0.02444352614304746.png",
  		"scanId" : "1pXnuDYAj8r",
  		"viewpointId" : "163d61ac7edb43fb958c5d9e69ae11ad"
  	},
  	{
  		"elevation" : -0.00068389140394051673,
  		"heading" : 5.8441199099264436,
  		"reference_image" : "29hnd4uzFmX_1576d62e7bbb45e8a5ef9e7bb37b1839_5.
  844119909926444_-0.0006838914039405167.png",
  		"scanId" : "29hnd4uzFmX",
  		"viewpointId" : "1576d62e7bbb45e8a5ef9e7bb37b1839"
  	}
  ]
  MatterSim: Could not open skybox RGB files at: ./data/v1/scans//17DRP5sb8fy/
  matterport_skybox_images/85c23efeaecd4d43a7dcd5b90137179e_skybox_small.jpg

===============================================================================
test cases:      5 |      4 passed | 1 failed
assertions: 119188 | 119187 passed | 1 failed

```
I noticed that the path `./data/v1/scans//17DRP5sb8fy/` is wrong but I don't what caused this issue. I think I have mounted the data folder correctly when launching the docker container because I can see my `17DRP5sb8fy` here as `/root/mount/Matterport3DSimulator/data/v1/scans/17DRP5sb8fy` with the right subfolders
```
cameras              image_overlap_data            matterport_camera_poses  matterport_depth_images  matterport_mesh           poisson_meshes        undistorted_camera_parameters  undistorted_depth_images
house_segmentations  matterport_camera_intrinsics  matterport_color_images  matterport_hdr_images    matterport_skybox_images  region_segmentations  undistorted_color_images       undistorted_normal_images
```

**Comment by ZhangTianrong** [comment]
Also, it seems that I don't have that file even if the path is corrected. What I have are
```
85c23efeaecd4d43a7dcd5b90137179e_skybox0_sami.jpg
85c23efeaecd4d43a7dcd5b90137179e_skybox1_sami.jpg
85c23efeaecd4d43a7dcd5b90137179e_skybox2_sami.jpg
85c23efeaecd4d43a7dcd5b90137179e_skybox3_sami.jpg
85c23efeaecd4d43a7dcd5b90137179e_skybox4_sami.jpg
85c23efeaecd4d43a7dcd5b90137179e_skybox5_sami.jpg
```
rather than `85c23efeaecd4d43a7dcd5b90137179e_skybox_small.jpg`

**Comment by Ber666** [comment]
Have you solved the problem?

**Comment by tenebrissilvam** [comment]
Hi, I have the same error, have anyone solved this problem?

**Comment by LuoXubo** [comment]
Hi, I met the same problem when testing the R2R room. And it reports the error like:

```
root@c5e710f62265:~/mount/Matterport3DSimulator# python3 tasks/R2R/eval.py 
Image features not provided
Loading navigation graphs for 61 scans
R2RBatch loaded with 14039 instructions, using splits: train
Traceback (most recent call last):
  File "tasks/R2R/eval.py", line 143, in <module>
    eval_simple_agents()
  File "tasks/R2R/eval.py", line 120, in eval_simple_agents
    agent.test()
  File "/root/mount/Matterport3DSimulator/tasks/R2R/agent.py", line 51, in test
    for traj in self.rollout():
  File "/root/mount/Matterport3DSimulator/tasks/R2R/agent.py", line 67, in rollout
    } for ob in self.env.reset()]
  File "/root/mount/Matterport3DSimulator/tasks/R2R/env.py", line 221, in reset
    self.env.newEpisodes(scanIds, viewpointIds, headings)
  File "/root/mount/Matterport3DSimulator/tasks/R2R/env.py", line 56, in newEpisodes
    self.sim.newEpisode(scanIds, viewpointIds, headings, [0]*self.batch_size)
IndexError: map::at
```

Does anyone know how to solve this problem?
